matrix:
  include:
    - language: c
      install:
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install -qq opam
        - opam install ocaml ocamlfind ounit dune
        - opam init
        - eval `opam config env`
      script:
        - cd ocaml
        - bash -ex .travis-ci-ocaml.sh

    - language: bash
      install:
      before_script:
        - sudo apt-add-repository ppa:swi-prolog/devel -y
        - sudo apt-get update -qq
        - sudo apt-get install --allow-unauthenticated swi-prolog-nox
      script:
        - cd prolog
        - bash -ex .travis-ci-prolog.sh

