matrix:
  include:
    - name: OCaml
    - language: bash
      install:
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install -qq ocaml opam
        - export OPAMYES=1
        - opam init
        - opam install ocamlfind ounit dune
        - eval `opam config env`
      script:
        - cd ocaml
        - bash -ex .travis-ci-ocaml.sh

    - name: Prolog
    - language: bash
      install:
      before_script:
        - sudo apt-add-repository ppa:swi-prolog/devel -y
        - sudo apt-get update -qq
        - sudo apt-get install --allow-unauthenticated swi-prolog-nox
      script:
        - cd prolog
        - bash -ex .travis-ci-prolog.sh

