matrix:
  include:
    - language: c
      script:
        - cd ocaml
        - bash -ex .travis-ci-ocaml.sh

    - language: bash
      install:
      before_script:
        - sudo apt-add-repository ppa:swi-prolog/devel -y
        - sudo apt-get update -q
        - sudo apt-get install --allow-unauthenticated swi-prolog-nox
      script:
        - cd prolog
        - bash -ex .travis-ci-prolog.sh

